name=SerialLED
version=1.0.0
author=InquisitiveMind123
maintainer=InquisitiveMind123
sentence=Serial-like data transmission through an LED.
paragraph=SerialLED provides a familiar Arduino Print API for simple optical data transmission using an onboard or external LED.
category=Communication
url=https://github.com/InquisitiveMind123/SerialLED
architectures=*
includes=SerialLED.h
